### PR TITLE
Adding Labs page

### PR DESCRIPTION
**Pull request by paulina-pacheco**

### CODE REVIEW

**Comment by paulina-pacheco** [comment]
@echavezNS if possible, can you take a look at this pull request?

**Comment by echavezNS** [comment]
Sure, I will take a look

**Comment by echavezNS** [comment]
@paulina-pacheco Can you create a new branch with this changes, so I can pull it and check how it looks?

**Comment by echavezNS** [comment]
Nice work Paulina, I let some comments about some small details, but great work.

image

**Comment by paulina-pacheco** [comment]
great, thank you @echavezNS. I forgot to add those icons. I will work on the details and update the pull request

**Comment by echavezNS** [comment]
any progress on this @paulina-pacheco ?

**Comment by paulina-pacheco** [comment]
I made some changes, please check :) @echavezNS

**Comment by echavezNS** [comment]
1280px width looks fine but this is how it looks for 500px width

image

I would suggest you to work with this media query

```CSS
@media(max-width: 500px) {
// all your styles here
}
```

That would be the last change I guess :)

**Comment by paulina-pacheco** [comment]
I updated this again with the media query you suggested

**Pull request merged**
